// app routes constant to navigate through app
const appRoutes = {
  PORTAL: 'portal',
  PORTAL_DASHBOARD: '/portal/dashboard',
  HOME: '/',
  LOGIN: '/login',
  NOT_FOUND: '*',
  LINKEDIN_CALLBACK: '/auth/linkedin/callback',
  CAMPAIGN_START: '/dashboard/campaigns/run',
  CAMPAIGN_UPDATE: '/dashboard/campaigns/update',
  RESET_PASSWORD: '/reset-password',
  CREATE_ACCOUNT: '/signup',
  EMPLOYER_SIGNUP: '/employers/signup',
  DASHBOARD: '/dashboard',
  USER_APPLICATIONS: '/dashboard/applications',
  APPLICATION_DETAILS: '/dashboard/applications/details',
  VACANCIES: '/dashboard/vacancies',
  SUBMIT_VACANCY: '/dashboard/vacancies/submit',
  EDIT_VACANCY: '/dashboard/vacancies/update',
  VACANCY_DETAILS: '/dashboard/vacancies/details',
  POSTS: '/dashboard/posts',
  ADD_POST: '/dashboard/posts/add',
  PAGES: '/dashboard/pages',
  ADD_PAGE: '/dashboard/pages/add',
  ADMINS_LIST: '/dashboard/admins',
  NEW_ADMIN: '/dashboard/admins/newadmin',
  EDIT_ADMIN: '/dashboard/admins/edit',
  BLOCK_LIST: '/dashboard/blocks',
  ADD_BLOCK: '/dashboard/blocks/add',
  CANDIDATES: '/dashboard/candidates',
  CANDIDATE_SIGNUP: '/candidates/signup',
  CANDIDATES_DETAILS: '/dashboard/candidates/details',
  CANDIDATES_EDIT: '/dashboard/candidates/edit',
  CLIENT_LIST: '/dashboard/clients',
  CLIENT_DETAILS: '/dashboard/clients/details',
  CLIENT_EDIT: '/dashboard/clients/edit',
  USER_PROFILE: '/dashboard/profile',
  PROFILE: 'profile',
  CV: 'cv',
  PREFERENCES: 'preferences',
  APPLICATIONS: 'applications',
  DETAILS: 'details',
  CANDIDATE_DETAIL_ROUTE: 'candidates/details',
  ADD_NOTE: 'notes/add',
  UPDATE_NOTE: 'notes',
  CLIENT_DETAIL_ROUTE: 'clients/details',
  PROSPECT_CLIENT_DETAILS: '/dashboard/prospect-clients/details',
};

export default appRoutes;
