const FORM_VALIDATION_MESSAGE = {
  FIRST_NAME: 'First name is required!',
  SURNAME: 'Surname is required!',
  EMAIL: 'Email address is required!',
  PHONE_NUMBER: 'Phone number is required!',
  COMPANY_NAME: 'Company Name is required!',
  ADDRESS_1: 'At least one address line is required!',
  TOWN: 'A town or city is required!',
  COUNTY: 'A county is required!',
  POSTCODE: 'A postcode is required!',
  COUNTRY: 'A country is required!',
  POSITION: 'The position is required.',
  SALARY: 'The salary must be greater than 0.',
  CONTRACTED_HOURS: 'The contracted weekly hours must be greater than 0.',
  WORK_LOCATION: 'The location of work is required.',
  FILE: 'The File is required.',
  JOB_TYPE: 'Job type is required',
  FILE_TYPE: 'Upload files in below formats.',
  WEBSITE: 'Website is required!',
  EXTENSION: 'Extension is required!',
  JOB_TITLE: 'Job Title is required!',
  CONTACT_NUMBER: 'Contact number is required!',
  ASSIGN_TO: 'Person to be assign is required!',
  TEXT_LENGTH: 'Text must be less than 100 characters long.',
};
export default FORM_VALIDATION_MESSAGE;
