export const SERVER_PORT = 5000;
export const ERROR_MSG = {
  COUNTRY_ALREADY_EXIST: 'Country is already in the list',
  CITY_ALREADY_EXIST: 'City is already in the list',
  Language_ALREADY_EXIST: 'Language is already in the list',
  JOB_TYPE_ALREADY_EXIST: 'Job Type is already in the list',
  JOB_CAT_ALREADY_EXIST: 'Job Category is already in the list',
  ALREADY_REGISTER:
    "There was a problem creating your account. Are you sure you haven't already registered?",
  ADMIN_ALREADY_REGISTER:
    "There was a problem creating this admin account. Are you sure this admin haven't already registered?",
  PASSWORD_DO_NOT_MATCH: 'Password and Confirm Password are not matched.',
  SOMETHING_WRONG: 'Something went wrong!!!',
  USER_ROLE_NOT_EXCEPT: "User role can't be except 1,2,3,4",
  INVALID_EMAIL_OR_PASSWORD: 'Invalid Password.',
  NOT_REGISTERED_EMAIL: 'Provided email is not registered.',
  NOTICE_PERIOD_NOT_EXCEPT: "Notice Period types can't be except 0,1,2,3",
  APPLICATION_STATUS_NOT_EXCEPT: "Notice Period types can't be except 0,1,2,3",
  EMPLOYER_REGISTER: 'Already completed the registration.',
  NOT_FOUND: 'User not found.',
  NOT_LOGGED_IN: 'Unauthorized !',
  USER_DELETED: 'User with provided email is deleted.',
  ERROR: 'error',
  VACANCY_NOT_FOUND: 'Vacancy is not found.',
  RELOCATION: 'Relocation can not be except 1,2,3.',
  INVALID_FILE_FORMAT: 'File format is not valid.',
  INVALID_FILE_SIZE: 'File size is not valid.',
  INVALID_TOKEN: 'Invalid Token.',
  EXPIRED_TOKEN: 'Reset password token expired.',
  SOME_ERROR: 'Something went wrong.',
  CAMPAIGN_STATUS: 'Campaign status is not valid.',
  CAMPAIGN_NOT_FOUND: 'Campaign is not found.',
  CAMPAIGN_DATE_INVALID: 'Please enter proper dates.',
  APPLICATION_NOT_FOUND: 'Application Not Found.',
  APPLICATION:
    'You have already applied on this vacancy. your application is under in review.',
  CANDIDATE_NOT_FOUND: 'Candidate not found.',
  EMAIL_WITH_DIFFERENT_ROLE: 'Email already register with different role.',
  NOTES_NOT_FOUND: 'No notes found.',
  PROSPECT_CLIENT_STATUS: 'Prospect Client status is not valid.',
};

export const SUCCESS_MSG = {
  USER_CREATED: 'User created successfully.',
  ADMIN_CREATED: 'Admin created successfully.',
  ADMIN_UPDATED: 'Admin updated successfully.',
  USER_UPDATED: 'User Updated successfully.',
  ADDRESS_UPDATED: 'Address Updated successfully.',
  EMPLOYER_REGISTRATION: 'Successfully register as Employer.',
  NEW_VACANCY: 'Successfully added a new Vacancy.',
  PROFILE_UPDATED: 'Profile Updated successfully.',
  PREFERENCES_UPDATED: 'Job Preferences Updated.',
  APPROVE_VACANCY: ' Vacancy Approved Successfully!',
  REGISTER_CANDIDATE: 'Successfully register as Candidate.',
  RESET_PASSWORD_SUCCESS: 'You have successfully reset you password.',
  DISABLE_ADMIN_SUCCESS: 'You have successfully disable admin.',
  CLOSE_VACANCY: 'Vacancy closed successfully.',
  UPDATE_VACANCY: 'Vacancy Updated Successfully.',
  FILE_UPDATED: 'File Updated Successfully.',
  CAMPAIGN_CREATED: 'Campaign created successfully.',
  CAMPAIGN_UPDATED: 'Campaign updated successfully.',
  CAMPAIGN_STOP: 'Campaign stopped successfully..',
  CAMPAIGN_START: 'Campaign started successfully.',
  APPLICATION_CREATED: 'Application created successfully.',
  APPLICATION_APPROVE: 'Application approved successfully.',
  APPLICATION_SHORTLISTED: 'Application Shortlisted Successfully.',
  APPLICATION_ACCEPTED: 'Application accepted successfully.',
  APPLICATION_REJECTED: 'Application rejected.',
  CANDIDATE_REMOVE: 'You have successfully removed the candidate.',
  CLIENT_REMOVE: 'You have successfully removed the client.',
  CANDIDATE_UPDATED: 'Candidate profile updated successfully.',
  NOTES_ADD: 'Notes added successfully.',
  NOTES_UPDATE: 'Notes updated successfully.',
  NOTES_REMOVE: 'Notes removed successfully.',
  COUNTRY_ADDED: 'Country added successfully',
  CITY_ADDED: 'City added successfully',
  LANGUAGE_ADDED: 'Language added successfully',
  JOB_TYPE_ADDED: 'Job Type added successfully',
  JOB_CAT_ADDED: 'JobCategory added successfully',
  SKILLS_ADDED: 'Skills added successfully.',
  INVITE_CANDIDATES: 'Candidates Invited Successfully.',
  PROSPECT_CLIENT_ADDED: 'New Prospect Client added successfully.',
  PROSPECT_PEOPLE_REMOVE: 'Person removed successfully.',
  PROSPECT_ADDRESS_REMOVE: 'Address removed successfully.',
  PROSPECT_ADDRESS_ADD: 'New Address added successfully.',
  PROSPECT_PEOPLE_ADD: 'New Person added successfully.',
  CONVERT_TO_CLIENT: 'Converted to client successfully.',
  CONVERT_TO_CLIENT_UPDATE: 'Updated client details successfully.',
  CLOSED_CLIENT: 'Client closed successfully.',
};

export const EMAIL_MSG = {
  EMAIL_DEFAULT: 'future Employments',
  EMAIL_SEND_SUCCESS: 'The reset Password link has sent to your email address.',
  FORGET_EMAIL_SUBJECT: 'Do Not Reply: Future Employments - Forget Password.',
  VACANCY_APPROVE: 'Do Not Reply: Future Employments - Vacancy Approval.',
  APPLICATION_APPROVE:
    'Do Not Reply: Future Employments - Application Approval.',
  VACANCY_CLOSE: 'Do Not Reply: Future Employments - Vacancy Closing.',
  CAMPAIGN_START: 'Do Not Reply: Future Employments - Campaign Started.',
};

export const TIMELINE_MSG = {
  SET_EMAIL: 'Email Update',
  ADD_PROSPECTS: 'Add Prospects',
  SET_PROSPECTS: 'Set Prospects',
  UPDATE_REMINDER: 'Update Reminder',
  NEW_ADDRESS: 'Added New Address',
  NEW_PERSON: 'Added New Person',
  CLOSE_CLIENT: 'Client Closed',
};

export const TIMELINE_KEYS = {
  companyName: 'Company Name',
  website: 'Website',
  description: 'Description',
  personAssigned: 'Person Assigned',
  notes: 'Notes',
  reminderNote: 'Reminder Note',
  reminderType: 'Reminder Type',
  additionalEmails: 'Additional Emails',
  reminderDate: 'Reminder Date',
  addressLine1: 'Address Line 1',
  addressLine2: 'Address Line 2',
  city: 'City',
  county: 'County',
  postcode: 'Postcode',
  country: 'Country',
  firstName: 'First Name',
  lastName: 'Last Name',
  jobTitle: 'Job Title',
  email: 'Email',
  phoneNumber: 'Phone Number',
  mobileNumber: 'Mobile Number',
  status: 'Status',
};

export const ALLOWED_FILE_FORMATS = ['pdf', 'png'];
export const ALLOWED_FILE_SIZE = 2e6;

export const DATE_FORMAT = {
  DD_MM_YYYY: 'DD/MM/YYYY',
  MM_DD_YYYY: 'MM/DD/YYYY',
  YYYY_MM_DD: 'YYYY/MM/DD',
};
